<?xml version="1.0"?>

<!-- Revolute-Revolute Manipulator -->
<robot name="car_test" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Physical Constant Macros -->
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- Dimension Macros -->
    <xacro:property name="wheelRadius" value="0.20447" />
    <xacro:property name="wheelWidth" value="0.11684" />

	<xacro:property name="axelBoxSize" value="0.1" />
	<xacro:property name="axelBoxHight" value="${wheelRadius + 0.05}" />
	<xacro:property name="rearAxelLength" value="${carWidth + wheelWidth}" />
	<xacro:property name="frontAxelLength" value="${axelBoxSize}" />
	<xacro:property name="axelThickness" value="0.05" />


    <xacro:property name="carLength" value="1.94" />
    <xacro:property name="carWidth" value="0.76" />
    <xacro:property name="carHeight" value="${1.05 - 0.5 - axelBoxHight}" />

    <xacro:property name="carMass" value="10" />
    <xacro:property name="componentMass" value="5" />
    <xacro:property name="wheelMass" value="1" />
	<xacro:property name="wheelBase" value="1.359" />
	
	<xacro:property name="dummySize" value="0.1" />

	<xacro:property name="spinVisLength" value="${wheelRadius * 1.5}" />
	<xacro:property name="spinVisWidth" value="0.05" />
	<xacro:property name="spinVisDepth" value="0.01" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find description)/urdf/car_test.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find description)/urdf/car_test_materials.xacro" />
    
<!--_________________________________________ Body ______________________________________-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${dummySize} ${dummySize} ${dummySize}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${dummySize} ${dummySize} ${dummySize}" />
            </geometry>
        </collision>
    </link>

    <joint name="base_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="car_body"/>
        <origin xyz="0 0 ${-dummySize*0.5}"/> 
    </joint>

    <link name="car_body">
        <inertial>
            <origin xyz="0 0 ${-carHeight*0.5}"  rpy="0 0 0" /> 
            <mass value="${carMass}" />
      		<inertia
	  			ixx="${carMass / 12.0 * (carWidth*carWidth + carHeight*carHeight)}" ixy="0.0" ixz="0.0"
	  			iyy="${carMass / 12.0 * (carHeight*carHeight + carLength*carLength)}" iyz="0.0"
	  			izz="${carMass / 12.0 * (carLength*carLength + carWidth*carWidth)}"
			/>
        </inertial>
        <visual>
            <origin xyz="0 0 ${-carHeight*0.5}"  rpy="0 0 0" /> 
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${-carHeight*0.5}"  rpy="0 0 0" /> 
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
        </collision>
    </link>

    <!-- ______________________________________________Front Suspension_______________________________________________ -->
    <joint name="front_joint" type="revolute">
		<limit lower="-0.5" upper="0.5" effort="100" velocity="2" />
		<dynamics damping="0.7"/>
		<axis xyz="0 0 1" />
    	<parent link="car_body"/>
    	<child link="front_link"/>
    	<origin xyz="${wheelBase/2} 0.0 ${-carHeight}"/>
    </joint>

    <link name="front_link">
        <inertial>
            <mass value="${componentMass}" />
            <origin xyz="0 0 ${axelBoxHight/2}" rpy="0 0 0"/>
            <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${-axelBoxHight/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${axelBoxSize} ${axelBoxSize} ${axelBoxHight}" />
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${axelBoxHight/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${axelBoxSize} ${axelBoxSize} ${axelBoxHight}" />
            </geometry>
        </collision>
    </link> 

    <joint name="front_axel_joint" type="continuous" >
        <axis xyz="0 1 0" />
		<dynamics damping="0.1"/>
        <parent link="front_link" />
        <child link="front_axel_link" />
        <origin xyz="0 0 ${-axelBoxHight}" rpy="0 0 0"/>
    </joint>

    <link name="front_axel_link">
        <inertial>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${componentMass}" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${axelThickness} ${frontAxelLength} ${axelThickness}" />
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${axelThickness} ${frontAxelLength} ${axelThickness}" />
            </geometry>
        </collision>
    </link>
  

 <!--_____________________________________________Rear Suspension _______________________________________________________-->
    <joint name="rear_joint" type="fixed">
    	<parent link="car_body"/>
    	<child link="rear_link"/>
    	<origin xyz="-${wheelBase/2} 0.0 ${carHeight*-1.0}"/>
    </joint>

    <link name="rear_link">
        <inertial>
            <mass value="${componentMass}" />
            <origin xyz="0 0 ${-axelBoxSize/2}" rpy="0 0 0"/>
            <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${-axelBoxHight/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${axelBoxSize} ${axelBoxSize} ${axelBoxHight}" />
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${-axelBoxHight/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${axelBoxSize} ${axelBoxSize} ${axelBoxHight}" />
            </geometry>
        </collision>
    </link>

    <joint name="rear_axel_joint" type="continuous" >
        <axis xyz="0 1 0" />
		<dynamics damping="0.1"/>
        <parent link="rear_link" />
        <child link="rear_axel_link" />
        <origin xyz="0 0 ${-axelBoxHight}" rpy="0 0 0"/>
    </joint>

    <link name="rear_axel_link">
        <inertial>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${componentMass}" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${axelThickness} ${rearAxelLength} ${axelThickness}" />
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${axelThickness} ${rearAxelLength} ${axelThickness}" />
            </geometry>
        </collision>
    </link>
   


<!--____________________________________Wheels________________________________________-->
	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="fixed" >
        <parent link="front_axel_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 -${frontAxelLength/2} 0" rpy="0 0 0" />
    </joint>


    <link name="front_left_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
			<origin xyz="0 -${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 -${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth/2}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
			<origin xyz="0 -${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth/2}" />
            </geometry>
        </collision>
    </link>

	<!-- the front right wheel -->
        <joint name="front_right_wheel_joint" type="fixed" >
        <parent link="front_axel_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 ${frontAxelLength/2} 0" rpy="0 0 0" />
    </joint>

    <link name="front_right_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
			<origin xyz="0 ${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 ${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth/2}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
			<origin xyz="0 ${wheelWidth*0.25} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth/2}" />
            </geometry>
        </collision>
    </link>
    
	<!-- the back left wheel -->
    <joint name="rear_left_wheel_joint" type="fixed" >
        <parent link="rear_axel_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="0 -${rearAxelLength/2} 0" rpy="0 0 0" />
    </joint>

    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
			<origin xyz="0 -${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 -${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
			<origin xyz="0 -${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    
	<!-- the back right wheel -->
    <joint name="rear_right_wheel_joint" type="fixed" >
        <parent link="rear_axel_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="0 ${rearAxelLength/2} 0" rpy="0 0 0" />
    </joint>

    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="${carMass*0.05}" />
			<origin xyz="0 ${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
			<origin xyz="0 ${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
			<origin xyz="0 ${wheelWidth*0.5} 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

<!--________________________________________wheel_direction_bars_______________________________________________-->

	<!-- the back left wheel -->

	<joint name="left_spin_joint" type="fixed" >
        <parent link="rear_left_wheel_link" />
        <child link="left_spin_link" />
        <origin xyz="0 -${wheelWidth} 0" rpy="0 0 0" />
    </joint>

	<link name="left_spin_link">
        <visual>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${spinVisLength} ${spinVisDepth} ${spinVisWidth}" />
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${spinVisLength} ${spinVisDepth} ${spinVisWidth}" />
            </geometry>
        </collision>
    </link>

	<!-- the back right wheel -->

	<joint name="right_spin_joint" type="fixed" >
        <parent link="rear_right_wheel_link" />
        <child link="right_spin_link" />
        <origin xyz="0 ${wheelWidth} 0" rpy="0 0 0" />
    </joint>

	<link name="right_spin_link">
        <visual>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${spinVisLength} ${spinVisDepth} ${spinVisWidth}" />
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"  rpy="0 0 0" /> 
            <geometry>
                <box size="${spinVisLength} ${spinVisDepth} ${spinVisWidth}" />
            </geometry>
        </collision>
    </link>

<!--________________________________________control info_______________________________________________-->


	<transmission name="throttle">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="rear_axel_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor1">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="steering">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="front_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor2">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<joint name="laser" type="fixed">
		<origin xyz="1 0 0.05" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="laser_link" />
	</joint>
	
	<link name="laser_link">
		<visual>
			<geometry>
				<box size="0.00 0.05 0.06"/>
			</geometry>
			<material name="green"/>
		</visual>
		<inertial>
			<mass value="0.0000001"/>
			<origin xyz="0 0 0" />
			<inertia ixx="0.0001" ixy="0.0" ixz="0.0"
				iyy="0.0001" iyz="0.0" izz="0.00001"/>
		</inertial>
	</link>
</robot>
